apiVersion: ${version}
kind: <%= kind %>
metadata:
  labels:
  <% for(label in labels){ %>
${label.key}: ${label.value}
  <% } %>
spec:
  containers:
    - name: alpine
      image: alpine:3.12.3
      command:
        - cat
      tty: true
  <% if( dockerBuild() ){ %>
- name: docker
  image: docker:18.05-dind
  securityContext:
    privileged: true
  volumeMounts:
    - name: dind-storage
      mountPath: /var/lib/docker
  <% } %>
  <% if( dockerBuild() ){ %>
volumes:
  - name: dind-storage
    emptyDir: {}
  <% } else { %>
volumes: {}
  <% } %>