apiVersion: ${version}
kind: service
metadata:
  labels:
  <% for(label in hosts){ %>
${label.key}: ${label.value}
  <% } %>
spec:
  containers:
    - name: alpine
      image: alpine:3.12.3
      command:
        - cat
      tty: true
    - name: docker
      image: docker:18.05-dind
      securityContext:
        privileged: true
      volumeMounts:
